// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7-AbSoEqNipfiXzi1_pC6ouWX1TNBGT8',
    appId: '1:1084647833722:web:dfee1dd613159b3e9c7bc3',
    messagingSenderId: '1084647833722',
    projectId: 'food-delievery-7ed48',
    authDomain: 'food-delievery-7ed48.firebaseapp.com',
    storageBucket: 'food-delievery-7ed48.firebasestorage.app',
    measurementId: 'G-Q2EEV01HQ3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDv7kps2jIFM-yw-KXPilclX5YPo74kHac',
    appId: '1:1084647833722:android:9dae05087e4f49349c7bc3',
    messagingSenderId: '1084647833722',
    projectId: 'food-delievery-7ed48',
    storageBucket: 'food-delievery-7ed48.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANYOwoQnyPMx_UsyVBp_InponG_mBkM40',
    appId: '1:1084647833722:ios:061c9e14016e49b69c7bc3',
    messagingSenderId: '1084647833722',
    projectId: 'food-delievery-7ed48',
    storageBucket: 'food-delievery-7ed48.firebasestorage.app',
    iosBundleId: 'com.example.fooddelivery2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANYOwoQnyPMx_UsyVBp_InponG_mBkM40',
    appId: '1:1084647833722:ios:061c9e14016e49b69c7bc3',
    messagingSenderId: '1084647833722',
    projectId: 'food-delievery-7ed48',
    storageBucket: 'food-delievery-7ed48.firebasestorage.app',
    iosBundleId: 'com.example.fooddelivery2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA7-AbSoEqNipfiXzi1_pC6ouWX1TNBGT8',
    appId: '1:1084647833722:web:dd56803390a731ae9c7bc3',
    messagingSenderId: '1084647833722',
    projectId: 'food-delievery-7ed48',
    authDomain: 'food-delievery-7ed48.firebaseapp.com',
    storageBucket: 'food-delievery-7ed48.firebasestorage.app',
    measurementId: 'G-1LYGHB3MBV',
  );
}
